.PHONY: all build test test-integration coverage vet fmt lint run tidy envtest-assets

# Kubernetes version for envtest binaries (kube-apiserver + etcd).
ENVTEST_K8S_VERSION ?= 1.33
# setup-envtest tool version (backlog SEC3, "pin ENVTEST_TOOL_VERSION"). Pinned
# to a released tag matching the controller-runtime minor in go.mod
# (sigs.k8s.io/controller-runtime v0.24.0) instead of @latest, so the envtest
# binary set (kube-apiserver + etcd) CI downloads is reproducible and does not
# silently drift between runs. Bump together with go.mod's controller-runtime
# version; verify a new tag exists first with:
#   gh api repos/kubernetes-sigs/controller-runtime/tags --jq '.[].name' | grep tools/setup-envtest
ENVTEST_TOOL_VERSION ?= v0.24.1
SETUP_ENVTEST := go run sigs.k8s.io/controller-runtime/tools/setup-envtest@$(ENVTEST_TOOL_VERSION)

all: fmt vet verify-surface test build

build:
	go build -o bin/k8s-bridge ./cmd/k8s-bridge

# Layer 1: unit tests — fakes at every boundary, no network, always fast.
test:
	go test -race ./...

# Layer 2: integration tests — real kube-apiserver via envtest with the real
# JobSet CRD; Slurm stays faked. Downloads envtest binaries on first run.
#
# Fixed (audit AUD1): this used to be two invocations chained with `; \`. The
# first's `-run Integration` matched zero tests (no test name contains the
# substring "Integration"), and `; \` discards the exit code of everything
# but the final command, so that first invocation could never fail the
# target no matter what it did or didn't run. A single invocation with no
# -run filter executes every test in the package once (envtest-backed and
# fake-client tests alike) and its exit code is now the target's exit code.
test-integration:
	KUBEBUILDER_ASSETS="$$($(SETUP_ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" \
		go test -race -tags integration -v ./internal/bridge/... ./internal/raybridge/...

coverage:
	go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out | tail -1

verify-surface:
	./scripts/verify-thin-surface.sh

vet:
	go vet ./...

fmt:
	gofmt -l -w .

# golangci-lint is optional locally (CI always runs it).
lint:
	@command -v golangci-lint >/dev/null 2>&1 \
		&& golangci-lint run ./... \
		|| echo "golangci-lint not installed locally - CI will run it (brew install golangci-lint)"

tidy:
	go mod tidy

# Layer 3 (E2E) is the assertion-annotated runbook: experiments/DEMO.md
# — it needs a live GKE cluster and is run manually / per session.
run: build
	./bin/k8s-bridge --config config/example-config.yaml

# --- Appended by the CI quality-gates pass (backlog AUD5 remainder) ---
# Kept append-only at the end of the file: a concurrent session owns the
# targets above and reformats/edits them independently.

.PHONY: fuzz bench-baseline bench-check coverage-check e2e-kind

# fuzz runs every FuzzXxx target in the module for a short, CI-affordable
# duration (backlog AUD5). 30s/target keeps the nightly workflow (see
# .github/workflows/nightly.yaml) well under typical job timeouts while
# still exercising far more input space than the seed corpus alone.
# FUZZTIME is overridable, e.g. `make fuzz FUZZTIME=5m` for a deeper local run.
FUZZTIME ?= 30s
fuzz:
	go test ./internal/slurm/... -run '^$$' -fuzz=FuzzGPUsPerNode -fuzztime=$(FUZZTIME)
	go test ./internal/slurm/... -run '^$$' -fuzz=FuzzJobEnvelopeDecode -fuzztime=$(FUZZTIME)
	go test ./internal/config/... -run '^$$' -fuzz=FuzzConfigLoad -fuzztime=$(FUZZTIME)

# bench-baseline regenerates test/bench-baseline.txt from a fresh local run.
# Not run by CI (CI compares against a freshly-run "before" measurement on
# the same runner instead, see the ci.yaml benchmark-regression step) — this
# target is for a human deliberately refreshing the committed reference
# after a real, intentional performance change.
bench-baseline:
	{ \
		echo "# Benchmark regression baseline (backlog AUD5)."; \
		echo "# Regenerated by 'make bench-baseline' on $$(date -u +%Y-%m-%dT%H:%M:%SZ)."; \
		echo "# See test/bench-baseline.txt history (git log -p) for the ratchet convention."; \
		go test -bench=. -benchtime=1000x -count=6 -run=NoTests ./internal/translate/...; \
		go test -bench=BenchmarkTick -benchtime=1000x -count=6 -run=NoTests ./internal/bridge/...; \
	} | tee test/bench-baseline.txt.new
	@echo "Review test/bench-baseline.txt.new, then: mv test/bench-baseline.txt.new test/bench-baseline.txt"

# bench-check runs the same benchmarks as the committed baseline and prints a
# benchstat comparison against test/bench-baseline.txt. This is what the CI
# benchmark-regression step also runs; kept as a Makefile target so a
# developer can reproduce a CI failure locally with one command. Written to a
# temp file rather than process substitution (<(...)) — make's default SHELL
# is /bin/sh, which does not support it on every platform this repo targets.
bench-check:
	go test -bench=. -benchtime=1000x -count=6 -run=NoTests ./internal/translate/... > /tmp/k8s-bridge-bench-after.txt
	go test -bench=BenchmarkTick -benchtime=1000x -count=6 -run=NoTests ./internal/bridge/... >> /tmp/k8s-bridge-bench-after.txt
	go run golang.org/x/perf/cmd/benchstat@latest test/bench-baseline.txt /tmp/k8s-bridge-bench-after.txt

# coverage-check reproduces the CI coverage-ratchet gate locally: total
# coverage (measured the same way as CI, -coverpkg=./... so cross-package
# calls count) must not drop below the floor hard-coded in ci.yaml.
coverage-check:
	go test -coverpkg=./... -coverprofile=/tmp/k8s-bridge-coverage.out ./...
	go tool cover -func=/tmp/k8s-bridge-coverage.out | tail -1

# e2e-kind runs the reduced-scope kind e2e smoke test locally (see
# test/e2e/run.sh header for scope/rationale). Requires kind, docker, kubectl
# on PATH; not part of `make all` since it needs a container runtime and
# takes minutes, not seconds.
e2e-kind:
	./test/e2e/run.sh

.PHONY: e2e-kind-real-slurm

# e2e-kind-real-slurm runs the REAL-Slurm lifecycle e2e (see
# test/e2e/run-real-slurm.sh header): a real slurmctld+slurmrestd as docker
# containers on the kind network, and the full hold->translate->admit->
# register->release->cleanup chain asserted in stages S1-S7. Additionally
# requires helm, jq, openssl, and a Linux docker host for the S5-S7 stages
# (on Docker Desktop/macOS those soft-fail by design — the CI runner in
# .github/workflows/e2e-slurm.yaml is the reference environment).
e2e-kind-real-slurm:
	./test/e2e/run-real-slurm.sh

# --- ADR-0014: typed WorkloadMixing API — codegen + generated CRD manifests ---
# Appended as its own section, same convention as the CI-quality-gates block
# above.

.PHONY: generate manifests

# controller-gen (sigs.k8s.io/controller-tools) version, pinned like
# ENVTEST_TOOL_VERSION above instead of @latest so the generated deepcopy/CRD
# output is reproducible and cannot silently drift between runs (the CI
# manifests-drift gate diffs the generated files, so an unpinned tool bump
# would fail every unrelated PR the day a new controller-tools releases).
# v0.21.0 is the newest release and is built against k8s.io/apimachinery
# v0.36.x — the same API-machinery minor as this module's go.mod — so the
# markers it understands and the schemas it emits match the libraries the
# controller links. Bump deliberately, together with the k8s.io/* deps, and
# re-run `make manifests` in the same change.
CONTROLLER_GEN_VERSION ?= v0.21.0
CONTROLLER_GEN := go run sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_GEN_VERSION)

# generate refreshes api/*/zz_generated.deepcopy.go from the +kubebuilder
# markers (DeepCopy/DeepCopyObject are what make the typed structs usable as
# controller-runtime client.Objects).
generate:
	$(CONTROLLER_GEN) object paths=./api/...

# The three shipped locations of the WorkloadMixing CRD. deploy/crd/ is the
# canonical deployable artifact; the chart copy exists because Helm only
# auto-installs CRDs from the chart's own crds/ directory; the test copy is
# what envtest loads (integration_test.go). All three are GENERATED from
# api/v1alpha1 — chart-ci's crd-sync-gate proves they stay spec-identical and
# ci.yaml's manifests-drift job proves they match the Go markers.
CRD_COPIES := \
	deploy/crd/workloadmixing-crd.yaml \
	deploy/chart/k8s-bridge/crds/workloadmixing-crd.yaml \
	test/crd/workloadmixing-crd.yaml

# manifests regenerates the CRD YAML from the typed API (ADR-0014: the CRD is
# a build artifact, not a hand-written file). Each destination's leading
# comment block (everything up to the first non-# line) is preserved across
# regeneration — the headers carry per-location context (Helm crds/ caveats,
# envtest role) that controller-gen knows nothing about.
#
# crd:allowDangerousTypes=true: controller-gen refuses float fields by
# default (floats are discouraged in APIs because of equality/rounding
# semantics). spec.slurmRequestsPerSecond has been `type: number` since the
# field was introduced (config.Config uses float64 — fractional rates like
# 0.5 rps are meaningful for a client-side limiter), so the flag documents
# an existing, deliberate schema choice rather than adding a new one.
manifests: generate
	@set -e; \
	tmp=$$(mktemp -d); \
	trap 'rm -rf "$$tmp"' EXIT; \
	$(CONTROLLER_GEN) crd:allowDangerousTypes=true paths=./api/... output:crd:artifacts:config="$$tmp"; \
	gen="$$tmp/k8s-bridge.x-k8s.io_workloadmixings.yaml"; \
	for dest in $(CRD_COPIES); do \
		awk '/^#/ { print; next } { exit }' "$$dest" > "$$tmp/header"; \
		cat "$$tmp/header" "$$gen" > "$$dest"; \
		echo "wrote $$dest"; \
	done

# The manifests-parity target (ADR-0014 PR-1 acceptance gate: prove the
# generated CRD semantically identical to a frozen pre-migration snapshot in
# hack/) was retired in PR 2, exactly as its own comment planned: PR 2
# deliberately changes the schema (status.conditions -> metav1.Condition), so
# the frozen reference stopped being a truth to compare against. The LASTING
# gates are manifests-drift (ci.yaml) and crd-sync-gate (chart-ci.yaml).
