#!/usr/bin/env bash
# serve.sh — launches the single-screen k8s-bridge demo console.
#
# Starts three local processes, all bound to 127.0.0.1 (see README security
# notes — this exposes a real shell, never bind to 0.0.0.0 or expose the
# port publicly):
#   1. ttyd    — a web terminal wrapping a real shell over websockets.
#                Typed commands in the browser run against this shell, so
#                the presenter can paste/type kubectl/sbatch/gcloud commands
#                without leaving the page.
#   2. status-api.js — tiny Node HTTP server exposing kubectl-derived
#                cluster/bridge/Slurm state as JSON (used by the page when
#                no Grafana URL is configured).
#   3. static-server.js — serves index.html/app.js/style.css for the page.
#
# Usage:
#   ./serve.sh                              # defaults everywhere
#   GRAFANA_URL=http://localhost:3000/d/xyz ./serve.sh   # embed Grafana instead
#   TTYD_PORT=7681 STATUS_PORT=8843 PAGE_PORT=8842 ./serve.sh
#
# Requires: ttyd (brew install ttyd), node, bash, kubectl on PATH and
# pointed at your cluster (kubectl config current-context). None of this
# script starts a cluster — see experiments/DEMO.md for that.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TTYD_PORT="${TTYD_PORT:-7681}"
STATUS_PORT="${STATUS_PORT:-8843}"
PAGE_PORT="${PAGE_PORT:-8842}"
GRAFANA_URL="${GRAFANA_URL:-}"
DEMO_SHELL="${DEMO_SHELL:-${SHELL:-/bin/zsh}}"

BIND_ADDR="127.0.0.1"

PIDS=()
cleanup() {
  echo
  echo "Shutting down demo console…"
  for pid in "${PIDS[@]:-}"; do
    kill "$pid" >/dev/null 2>&1 || true
  done
}
trap cleanup EXIT INT TERM

echo "== k8s-bridge demo console =="
echo

# --- 1. Check ttyd ---------------------------------------------------------
if ! command -v ttyd >/dev/null 2>&1; then
  cat <<'EOF'
ttyd is not installed — it is what puts a real terminal in the browser tab
so you can type commands directly in the demo UI.

Install it (macOS):
  brew install ttyd

Then re-run this script. (Linux: your distro's package manager, or see
https://github.com/tsl0922/ttyd#installation)
EOF
  exit 1
fi

echo "[1/3] Starting ttyd (web terminal) on ${BIND_ADDR}:${TTYD_PORT}"
echo "      Shell: ${DEMO_SHELL}"
# -W enables client input (writable) — required for the "type commands
# directly" requirement; without it ttyd would be read-only/view-only.
# --interface accepts an IP address as the bind address (ttyd defaults to
# all interfaces otherwise) — this is what keeps the exposed shell off the
# network. Do not remove this flag; see README security notes.
ttyd --interface "${BIND_ADDR}" --port "${TTYD_PORT}" -W "${DEMO_SHELL}" >/tmp/demo-console-ttyd.log 2>&1 &
TTYD_PID=$!
PIDS+=("${TTYD_PID}")
sleep 1
if ! kill -0 "${TTYD_PID}" >/dev/null 2>&1; then
  echo "ttyd failed to start — see /tmp/demo-console-ttyd.log:"
  cat /tmp/demo-console-ttyd.log
  exit 1
fi

# --- 2. status API ----------------------------------------------------------
echo "[2/3] Starting status API on ${BIND_ADDR}:${STATUS_PORT}"
node "${SCRIPT_DIR}/status-api.js" "${STATUS_PORT}" >/tmp/demo-console-status.log 2>&1 &
STATUS_PID=$!
PIDS+=("${STATUS_PID}")
sleep 0.3

# --- 3. static page server ---------------------------------------------------
echo "[3/3] Starting static page server on ${BIND_ADDR}:${PAGE_PORT}"

# Bake the real ports/URLs into config.js so the page doesn't need query
# params. This OVERWRITES tools/demo-console/config.js on every launch —
# it is generated, not hand-edited (the checked-in version is just a
# same-origin-guessing fallback for opening index.html without serve.sh).
cat > "${SCRIPT_DIR}/config.js" <<EOF
// GENERATED by serve.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ') — do not edit by hand.
window.DEMO_CONSOLE_CONFIG = {
  ttydUrl: "http://${BIND_ADDR}:${TTYD_PORT}",
  statusApiUrl: "http://${BIND_ADDR}:${STATUS_PORT}/status",
  grafanaUrl: "${GRAFANA_URL}"
};
EOF

node "${SCRIPT_DIR}/static-server.js" "${PAGE_PORT}" "${SCRIPT_DIR}" >/tmp/demo-console-page.log 2>&1 &
PAGE_PID=$!
PIDS+=("${PAGE_PID}")
sleep 0.3

echo
echo "== Ready =="
echo "Open this ONE url and present from it:"
echo
echo "    http://${BIND_ADDR}:${PAGE_PORT}/"
echo
if [ -n "${GRAFANA_URL}" ]; then
  echo "Dashboards: embedding Grafana at ${GRAFANA_URL}"
else
  echo "Dashboards: no GRAFANA_URL set — showing the bridge-top-style status strip instead."
  echo "            (set GRAFANA_URL=http://... and re-run to embed Grafana)"
fi
echo
echo "Terminal: ttyd on http://${BIND_ADDR}:${TTYD_PORT} (embedded in the page)."
echo "Everything is bound to ${BIND_ADDR} only — do not port-forward or"
echo "expose these ports beyond localhost (see README security notes)."
echo
echo "Press Ctrl+C to stop all three processes."
echo

wait
