apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ray-bridge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ray-bridge.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
